apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:latest 
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "mydatabase"
        volumeMounts:
        - name: db-credentials
          mountPath: /etc/db-credentials
      volumes:
      - name: db-credentials
        hostPath:
          path: /path/to/your/db-credentials  
