apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306        # المنفذ الذي ستستخدمه الخدمة
      targetPort: 3306  # المنفذ الذي يستمع عليه MySQL داخل الـPod
