apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    app: proxy
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
    - port: 443      # منفذ الخدمة
      targetPort: 443 # منفذ التطبيق داخل الـPod
      nodePort: 30080  # المنفذ الذي سيتم فتحه على كل عقدة (Node) للوصول من الخارج
